### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by nucleartide** [jamesmcnamara/shades#14]
Hey James, I couldn't find you on Twitter but great talk at Reactathon! Will definitely look into using this library in the future.

This isn't really an issue (so feel free to close), but I thought it'd be funny to use the `shades` logo in a "deal with it" joke: 😂 

![deal_with_it3](https://user-images.githubusercontent.com/914228/45264267-ba100300-b3ee-11e8-966d-ee6b39a3ba60.gif)

Thanks for the awesome library!

**Comment by jamesmcnamara** [comment]
Hahahah I love it! I'll have to find a way to incorporate this.

Great work :)

**Comment by jamesmcnamara** [comment]
Added to the front page :+1:

**Comment by nucleartide** [comment]
😂
