### ISSUE TITLE
How to deal with UUID's that start with a number?

### ISSUE THREAD

**Issue by iwakoscott** [jamesmcnamara/shades#15]
#### Issue
I've run into an issue when I have a UUID that begins with a number. For example, if I have data stored at the UUID `8c826e4a0fa442d085959a6ce657fa55`, I am getting the following error when trying to use `set`.

<img width="724" alt="screen shot 2018-10-01 at 11 32 17 am" src="https://user-images.githubusercontent.com/13685868/46308262-070a7380-c56e-11e8-9bce-41c0ae52214c.png">

#### My Question:
Is using UUID's that begin with a number bad practice to begin with? Or, is there a work around for this that I can't seem to find in the documentation? Thanks in advance!

#### Codesandbox Demo:
https://codesandbox.io/s/8xyjyl3672

**Comment by jamesmcnamara** [comment]
Sorry I just saw this!

I'm currently working on a 2.0 version of this library that, among other things, removes the parser in favor of separate strings and numbers.

For example
```js
set('foo.bar[0].baz')
```
will become
```js
set('foo', 'bar', 0, 'baz')
```

This will enable allow us to strongly type shades, remove all of the parsing and compiling, and will solve this issue along the way :)

I'll let you know as soon as the beta is out.

**Comment by iwakoscott** [comment]
Awesome! Can't wait for this new update!

**Comment by jamesmcnamara** [comment]
Sorry for the huge delay, but a preview of 2.0 is now available! You can install it with
```sh
npm i shades@beta
```

**Comment by iwakoscott** [comment]
Sounds good to me. Thanks for all of your hard work!
