### ISSUE TITLE
cons (push) opposite: unshift?

### ISSUE THREAD

**Issue by oluckyman** [jamesmcnamara/shades#24]
Is there the opposite for `cons`? which will insert an element into beginning?
And if no, what's the shades-style to achieve it?

**Comment by jamesmcnamara** [comment]
As of [shades@2.1.0-beta.1](https://github.com/jamesmcnamara/shades/commit/00fa366b15619e9a9e8a77fc2db820cf5d97b07d), there's an [`unshift`](https://github.com/jamesmcnamara/shades#unshift) function!

```ts
> unshift(1)([2, 3, 4])
[1, 2, 3, 4]
```

You can grab it by doing 
```shell
npm install shades@beta
```

Or if you want to stick with the stable branch, you can do:
```ts
> prepend([1])([2, 3, 4])
[1, 2, 3, 4]
```
*Note that prepend requires that the first element be a list as well.*

**Comment by oluckyman** [comment]
ah, thanks! missed the `prepend` or was not aware that it's what I need. Ended up by using 
```
x => xs => [x, ...xs]
```
which is pretty concise too.

offtop suggestion: Table of contents for API would be helpful. To see all the methods at a glance
