### ISSUE TITLE
Types not resolving properly with TypeScript 3.8.2 

### ISSUE THREAD

**Issue by cowboyd** [jamesmcnamara/shades#36]
Hello,

Thank you for the great library and the thoughtful README. This api is very user-friendly. 

I'm evaluating shades as a replacement for ramda lenses since we're having a devil of a time with Ramda lenses and TS. Shades looks like it's got a lot of promise in this direction, so we're very interested in seeing how it will work.

I ran into a stumbling block pretty early on when composing lenses with the `get` method. TypeScript thinks that `get('user', 'username')` is a function that returns `undefined`. Specifically

`<S extends HasKey<"user", HasKey<"username", any>>>(s: S) => undefined`

The `get` itself works, but you can't actually use any values produced by it in TypeScript because the compiler thinks it's `undefined` and therefore unsafe.

Here are some screenshots showing the errors:

![image](https://user-images.githubusercontent.com/4205/75074679-cd6b3d00-54c1-11ea-80d9-c0d01a0afb78.png)

![image](https://user-images.githubusercontent.com/4205/75074805-13c09c00-54c2-11ea-9f5d-421e477668fb.png)

![image](https://user-images.githubusercontent.com/4205/75074902-410d4a00-54c2-11ea-9d97-d20e9ed7df20.png)

Here is the repo I'm using https://github.com/cowboyd/shades-test

**Comment by jamesmcnamara** [comment]
Oooh very interesting. I haven't tested this with 3.7 or above, I'll try to carve some time and investigate. Handling possibly undefined values has been a real bear for this library.

**Comment by jamesmcnamara** [comment]
This is resolved in later versions of TS; I'm publishing shades@2.2 later today which will update all dependencies.
