### ISSUE TITLE
export compose function

### ISSUE THREAD

**Issue by ptpaterson** [jamesmcnamara/shades#43]
compose is not exported, but I think it would be helpful to have available for building custom lenses.

In my case, I am using custom lenses to build database queries.  I have a `prop` lens, and also a `path` that is the composition of multiple `prop`s. Since I cannot just use default compiled props, I end up with `get(prop('one'), prop('two'), /*...*/)` so it's nicer to compose them behind the scenes: `get(path('one', 'two'), /*...*/))`

**Comment by jamesmcnamara** [comment]
Exported in `shades@2.2`
