### ISSUE TITLE
[Question] max 6 arguments

### ISSUE THREAD

**Issue by JesseZomer** [jamesmcnamara/shades#49]
Hello 👋,

I've been trying this pretty amazing library. One thing I've run into is that it you can only have max 6 arguments.
We have a pretty nested view (calendar with week, days, appointments..) and sometimes I need 7 or 8 arguments

example: `mod('view', 'weeks' , matching(currentWeek), 'days', matching(currentDay), 'appointments', matching(appWithId(..)).`
Is there anyway to combine lenses like
```javascript
const currentDay = mod('view', 'weeks' , matching(currentWeek), 'days', matching(currentDay));
mod(currentDay, 'appointments')
```
or something like that? Or is there another way to best handle this kind of problem?

Also if I want to remove an element from an array is this the way to do it: 
```javascript
   mod('days',  matching(currentDay)) ( (day) => ({...day, appointments: day.appointments.filter(...)})) (data)
```
   or is there someway I can go to the appointments in the lens and use a filter fn like:
```javascript
   mod('days',  matching(currentDay), 'appointments') (filter(not({ id: appointmentId })) (data) 
```

Thanks for the cool library 👍

**Comment by jamesmcnamara** [comment]
Hey glad you are enjoying it! 

The reason for the six argument limit is that we programmatically generate overrides for each of the methods based on all the different combinations of input types (string, number, traversal and virtual lens). With four possibilities for each position, every additional parameter adds an exponential amount of new overrides. With 6, we have over 50,000 lines of typings. Above that, the TypeScript server really slows down. 

As a workaround, you can just nest a second call to `mod` as your transformer function, i.e.:
```ts
mod('view', 'weeks' , matching(currentWeek), 'days', matching(currentDay), 'appointments')(mod(matching(appWithId(..)), 'more', 'keys')(myTransformer))
```
`mod` applied to a series of lenses is just expecting a function that goes from the focus of the lens `S` to `S`. Separately, `mod` applied to a series of lenses and a transformer function from `T` to `T` (where T is the focus of the new lens) produces a function that goes from `S` to `S`. So `mod` applied twice is a perfect candidate for mod applied once. Pretty cool.

There is the possibility that with nesting you might confuse TS, but you can always add an explicit argument signature to the inner function and it should figure it out:
```ts
mod('view', 'weeks' , matching(currentWeek), 'days', matching(currentDay), 'appointments')((appointments: Appointment[]) => mod(matching(appWithId(..)), 'more', 'keys')(myTransformer)(appointments)
```

As for the filtering question, yes I think that's a very reasonable way to do it.

**Comment by ptpaterson** [comment]
I noted this elsewhere too, but I think[ Variadic Tuple Types](https://devblogs.microsoft.com/typescript/announcing-typescript-4-0-beta/#variadic-tuple-types) coming in TS4 should help, or maybe be able to eliminate all the overloading.
