### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by arturohernandez10** [jamesmcnamara/shades#51]
I think yours is probably the better implementation of lenses for Javascript. Can you give us a project status? Are you using it on production projects? Do you know if anyone does? Other than type issues, are there significant pending issues with the source base? Or do you think it is just very solid and it has not required maintenance.

As you can see these are just simple questions that people considering to use this library would want to ask. And it has been sometime since you last made an update.

**Comment by jamesmcnamara** [comment]
Sorry for the late reply. I am actively using this project in multiple production projects, but I have not had any time to make upgrades related to TS versions post 3.7.

However, I'm using it with TS 3.9 without issue. 

I would welcome any PRs for upgrading the dependencies or fixing open issues.
